#!/usr/bin/env bash

MOD="Control"
ROFI_PROMPT="Power:"
ROFI_CANCEL="${MOD}+p,${MOD}+space,Escape"

# menu defined as an associative array
typeset -A menu

menu[ Reboot]="systemctl reboot"
menu[ PowerOff]="systemctl poweroff" 
menu[󱞓 Suspend]="systemctl suspend" 
menu[󰍃 Logout]="i3-msg exit"

menu_keys=$(printf '%s\n' "${!menu[@]}")
max_length=$(echo "${menu_keys}" | awk '{ if (length > max) { max = length } } END { print max }')

ROFI_WIDTH=$((max_length + 2))
ROFI_OPTIONS=(-no-fixed-num-lines \ 
    -kb-cancel ${ROFI_CANCEL} \
    -theme ~/.config/rofi/custom-dmenu.rasi \
    -theme-str "window { 
        width: ${ROFI_WIDTH}ch; 
        location: south east; 
        y-offset: -28; 
    }"
)

launcher_exe="rofi"
launcher_options=(-i -lines "${#menu[@]}" -p "${ROFI_PROMPT}" "${ROFI_OPTIONS[@]}" -dmenu)
launcher=(${launcher_exe} "${launcher_options[@]}")
selection="$(printf '%s\n' "${!menu[@]}" | "${launcher[@]}")"

# the -n checks if string has non-zero length
if [[ -n "$selection" ]]; then
    i3-msg -q "exec --no-startup-id ${menu[${selection}]}"
fi


