#!/usr/bin/env bash

ROFI_PROMPT="Layout:"

# menu defined as an associative array
typeset -A menu

layouts=~/.dotEndeavor/config-stow/i3/.config/i3/layouts

# Menu with keys/commands
menu=(
    [[1] code]="i3-msg workspace 'Code' & i3-msg append_layout $layouts/coding.json" 
    [[2] term]="i3-msg append_layout $layouts/terminal.json" 
)
menu_nrows=${#menu[@]}

menu_keys=$(printf '%s\n' "${!menu[@]}")
max_length=$(echo "${menu_keys}" | awk '{ if (length > max) { max = length } } END { print max }')

ROFI_WIDTH=$((max_length + 2))
ROFI_OPTIONS=(-no-fixed-num-lines \ 
    -kb-cancel "Alt+o" \
    -theme ~/.config/rofi/custom-dmenu.rasi \
    -theme-str "window { width: ${ROFI_WIDTH}ch;}")

launcher_exe="rofi"
launcher_options=(-i -lines "${menu_nrows}" -p "${ROFI_PROMPT}" "${ROFI_OPTIONS[@]}" -dmenu)
launcher=(${launcher_exe} "${launcher_options[@]}")
selection="$(printf '%s\n' "${!menu[@]}" | "${launcher[@]}")"

# the -n checks if string has non-zero length
if [[ -n "$selection" ]]; then
    i3-msg -q "exec --no-startup-id ${menu[${selection}]}"
fi

