#!/usr/bin/env bash

ROFI_PROMPT="Profile:"

# use of parenthesis instead of quotations means this is an array (white space seperated)
menu=($(powerprofilesctl list | grep ':$' | sed 's/[* :]//g'))
menu_nrows=${#menu[@]}

max_length=$(echo "${menu}" | awk '{ if (length > max) { max = length } } END { print max }')

ROFI_WIDTH=$((max_length + 2))
ROFI_OPTIONS=(-no-fixed-num-lines \ 
    -theme ~/.config/rofi/custom-dmenu.rasi \
    -theme-str "window { width: ${ROFI_WIDTH}ch;}")

launcher_exe="rofi"
launcher_options=(-i -lines "${menu_nrows}" -p "${ROFI_PROMPT}" "${ROFI_OPTIONS[@]}" -dmenu)
launcher=(${launcher_exe} "${launcher_options[@]}")
selection="$(printf '%s\n' "${menu[@]}" | "${launcher[@]}")" 

# the -n checks if string has non-zero length
if [[ -n "$selection" ]]; then
    powerprofilesctl set $selection
fi

