live_config_reload = true
working_directory = "/home/farrukh/"

[colors.bright]
black = "#4C566A"
blue = "#81A1C1"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#ECEFF4"
yellow = "#EBCB8B"

[colors.cursor]
cursor = "#00CACA"
text = "#000000"

[colors.normal]
black = "#156BDC"
blue = "#F77067"
cyan = "#88C0D0"
green = "#2AACAA"
magenta = "#B48EAD"
red = "#F22C57"
white = "#E5E9F0"
yellow = "#EBCB8B"

[colors.primary]
background = "#1A1B26"
foreground = "#D8DEE9"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 9.0

[font.bold]
family = "Jetbrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Jetbrains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Jetbrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Jetbrains Mono Nerd Font"
style = "Regular"

[font.offset]
y = 6

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[D"
key = "H"
mode = "~Alt"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[B"
key = "J"
mode = "~Alt"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[A"
key = "K"
mode = "~Alt"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[C"
key = "L"
mode = "~Alt"
mods = "Alt"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"
mods = "None"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"
mods = "None"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mode = "~Alt"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mode = "~Alt"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "K"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "J"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Control"

# [mouse.double_click]
# threshold = 300
#
# [mouse.triple_click]
# threshold = 300

[scrolling]
history = 10000
multiplier = 3

[shell]
program = "/bin/zsh"

[window]
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 148
lines = 29

[window.padding]
x = 7
y = 7
