
[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "Jetbrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Jetbrains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Jetbrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Jetbrains Mono Nerd Font"
style = "Regular"

[font.offset]
y = 4

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0012"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001BD"
key = "Delete"
mods = "Control"

# [[keyboard.bindings]]
# chars = "\u001BD"
# key = "L"
# mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[D"
key = "H"
mode = "~Alt"
mods = "Alt"


[[keyboard.bindings]]
chars = "0xff95"
key = "H"
mode = "~Alt"
mods = "Alt|Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[B"
key = "J"
mode = "~Alt"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "L"
mode = "~Alt"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "H"
mode = "~Alt"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[A"
key = "K"
mode = "~Alt"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[C"
key = "L"
mode = "~Alt"
mods = "Alt"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"
mods = "None"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"
mods = "None"

# [[keyboard.bindings]]
# action = "ClearLogNotice"
# key = "L"
# mods = "Control"

# [[keyboard.bindings]]
# chars = "\f"
# key = "L"
# mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mode = "~Alt"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mode = "~Alt"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "K"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "J"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

# [[keyboard.bindings]]
# action = "Quit"
# key = "W"
# mods = "Control"

# [mouse.double_click]
# threshold = 300
#
# [mouse.triple_click]
# threshold = 300
#
[scrolling]
history = 10000
multiplier = 1

[terminal.shell]
program = "/bin/zsh"

[window]
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 140
lines = 30

[window.padding]
x = 7
y = 7

[general]
live_config_reload = true
working_directory = "$HOME"
import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]
# import = [ "~/.config/alacritty/tokyonigt.toml" ]

[terminal]
