# icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#16161e"
# idle_fg = "#abcdef"

# green #9ece6a
# purple #bb9af7
# red #f7768e
# blue #7aa2f7
# yellow #e0af68

good_bg = "#9ece6a"
good_fg = "#15161e"
info_bg = "#bb9af7"
info_fg = "#15161e"
warning_bg = "#e0af68"
warning_fg = "#15161e"
critical_bg = "#f7768e"
critical_fg = "#15161e"

[icons]
icons = "awesome5"
[icons.overrides]
# bat = ["|E|", "|_|", "|=|", "|F|"]
# bat_charging = ""
#
# [[block]]
# block = "load"
# format = " $icon 1min avg: $1m.eng(w:4) "
# interval = 1


[[block]]
merge_with_next = false 
block = "focused_window"
format = " {$title.str(max_w:80)|} "
[block.theme_overrides] # low priority
idle_bg = "#1a1b26"
idle_fg = "#7aa2f7"
# [block.format]
# full = " $title.str(max_w:15) |"
# short = " $title.str(max_w:10) |"


######################################
# System stats---------------------------------------------------------------------------------------------------------------------------------------
######################################



# cpu temprature
[[block]]
merge_with_next = true 
block = "temperature"
format = " $icon $average "
good = 40
idle = 50
info = 50
warning = 60
# command = "sensors|grep temp2: |  grep -oE '+[0-9]+.[0-9]+°C' | head -1 | sed 's/+//' | tr -d '\t\n\r'"
interval = 10
[[block.click]]
button = "left"
update = true
[block.theme_overrides] # low priority
idle_bg = "#16161e"

# cpu utilization
[[block]]
merge_with_next = false 
block = "cpu"
format = "$icon$utilization " 
# command = "sensors|grep temp2: |  grep -oE '+[0-9]+.[0-9]+°C' | head -1 | sed 's/+//' | tr -d '\t\n\r'"
interval = 30
[[block.click]]
button = "left"
update = true
[block.theme_overrides] # low priority
idle_bg = "#16161e"

# gpu
# [[block]]
# merge_with_next = false 
# block = "nvidia_gpu"
# format = "$icon $temperature$utilization "
# # format_alt = " $icon MEM: $vram_used_percents ($vram_used/$vram_total) "
# interval = 20
# [[block.click]]
# button = "left"
# update = true
# [block.theme_overrides] # low priority
# idle_bg = "#16161e"


# memory
[[block]]
merge_with_next = true 
block = "memory"
format = "$icon $mem_used.eng(w:3)"
format_alt = " $icon $mem_total$mem_total_used $mem_used.eng(w:4)"
interval = 30
warning_mem = 60
critical_mem = 80 
[[block.click]]
button = "right"
action = "toggle_format"
[[block.click]]
button = "left"
update = true
[block.theme_overrides] # low priority
idle_bg = "#16161e"

# dist space
[[block]]
merge_with_next = false 
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 300
warning = 20.0
alert = 10.0
[[block.click]]
button = "left"
update = true
[block.theme_overrides] # low priority
idle_bg = "#16161e"



######################################
# Date---------------------------------------------------------------------------------------------------------------------------------------
######################################



# multimedia
[[block]]
merge_with_next = true 
block = "music"
format = "{ $prev  $play  $next }|"
seek_step_secs = 60
# [[block.click]]
# button = "left on $prev"
# action = "prev"
# [[block.click]]
# button = "left on $play"
# action = "play_pause"
# [[block.click]]
# button = "left on $next"
# action = "next"
[block.theme_overrides] # mid priority
idle_bg = "#3b4261"
idle_fg = "#abcdef"

# timer
[[block]]
merge_with_next = true 
block = "tea_timer"
format = " $icon {$hours:$minutes:$seconds|} "
done_cmd = "notify-send 'Timer Finished'"
increment = 60
[[block.click]]
button = "down"
action = "increment"
[[block.click]]
button = "up"
action = "decrement"
[[block.click]]
button = "right"
action = "reset"
[block.theme_overrides] # mid priority
idle_bg = "#3b4261"
idle_fg = "#abcdef"

[[block]]
block = "time"
interval = 60
format = "$timestamp.datetime(f:'%a %-d-%b %I:%M %P') "
[block.theme_overrides] # mid priority
idle_bg = "#3b4261"
idle_fg = "#abcdef"



######################################
# Main stats---------------------------------------------------------------------------------------------------------------------------------------
######################################



# internet
[[block]]
merge_with_next = true 
block = "net"
# device = "wlp2s0"
format = " $icon {$ssid $signal_strength|} "
format_alt = " $icon {$ssid $signal_strength $speed_down.eng(w:3){,}$speed_up.eng(w:3) }|"
interval = 60
[[block.click]]
button = "left"
update = true
[[block.click]]
button = "right"
update = true
action = "toggle_format"
[block.theme_overrides] # high priority
idle_bg = "#7aa2f7"
idle_fg = "#16161e"

# bluetooth
[[block]]
merge_with_next = true 
block = "bluetooth"
mac = "84:AC:60:31:89:58"
disconnected_format = "$icon "
format = "$icon PEATS "
[block.battery_state]
"0..20" = "critical"
"21..22" = "warning"
"99..100" = "good"
[[block.click]]
button = "left"
update = true
[block.theme_overrides] # high priority
idle_bg = "#7aa2f7"
idle_fg = "#16161e"
good_bg = "#7aa2f7"

# # volume
# [[block]]
# merge_with_next = true 
# block = "sound"
# format = "$icon{$volume.eng(w:2)|} "
# headphones_indicator = true
# [[block.click]]
# button = "right"
# cmd = "pavucontrol"
# [[block.click]]
# button = "down"
# action = "volume_up"
# [[block.click]]
# button = "up"
# action = "volume_down"
# [block.theme_overrides] # high priority
# idle_bg = "#7aa2f7"
# idle_fg = "#16161e"

# battery
[[block]]
merge_with_next = false 
block = "battery"

# not full and unpluged format
format = " $icon {$percentage} {$time} "

# full battery format
full_format = "$icon {$percentage|} {$time} "
# not full and pluged in format
charging_format = "$icon {$percentage|} "
# empty and not plugged in format
empty_format = "$icon {$percentage|} {$time} "
# when full battery has reached
not_charging_format = "$icon {$percentage|} {$time} "

full_threshold = 80
empty_threshold = 60

device = "DisplayDevice"
driver = "upower"
interval = 60
good = 80
info = 80
warning = 65
critical = 60
[[block.click]]
button = "left"
update = true
[block.theme_overrides] # high priority
idle_bg = "#7aa2f7"
idle_fg = "#16161e"


