# icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#16161e"
# idle_fg = "#abcdef"

[icons]
icons = "awesome5"
# [icons.overrides]
# # bat = ["|E|", "|_|", "|=|", "|F|"]
# bat_charging = ""
#
# [[block]]
# block = "load"
# format = " $icon 1min avg: $1m.eng(w:4) "
# interval = 1

# multimedia
[[block]]
merge_with_next = false 
block = "music"
# format = " {$combo.str(max_w:30) $prev  $play  $next }|"
format = " {$combo.str(max_w:0) $prev  $play  $next }|"
seek_step_secs = 10
[[block.click]]
button = "up"
action = "volume_up"
[[block.click]]
button = "down"
action = "volume_down"
[[block.click]]
button = "forward"
action = "seek_forward"
[[block.click]]
button = "back"
action = "seek_backward"
[[block.click]]
button = "Right on $combo"
action = "next_player"

# [[block]]
# block = "temperature"
# format = " $icon $max max "
# format_alt = " $icon $min min, $max max, $average avg "
# interval = 5
# chip = "acpitz-acpi-0"

# cpu temprature
[[block]]
merge_with_next = true 
block = "temperature"
format = " $icon $average "
good = 40
idle = 50
info = 50
warning = 60
# command = "sensors|grep temp2: |  grep -oE '+[0-9]+.[0-9]+°C' | head -1 | sed 's/+//' | tr -d '\t\n\r'"
interval = 10
[[block.click]]
button = "left"
update = true

# cpu utilization
[[block]]
merge_with_next = true 
block = "cpu"
format = "$icon$utilization "
# command = "sensors|grep temp2: |  grep -oE '+[0-9]+.[0-9]+°C' | head -1 | sed 's/+//' | tr -d '\t\n\r'"
interval = 10
[[block.click]]
button = "left"
update = true

# gpu
[[block]]
merge_with_next = true 
block = "nvidia_gpu"
format = " $icon $temperature$utilization"
# format_alt = " $icon MEM: $vram_used_percents ($vram_used/$vram_total) "
interval = 20
[[block.click]]
button = "left"
update = true


# memory
[[block]]
merge_with_next = true 
block = "memory"
format = " $icon $mem_used.eng(w:3)"
format_alt = " $icon $mem_total$mem_total_used $mem_used.eng(w:4)"
interval = 30
warning_mem = 60
critical_mem = 80 
[[block.click]]
button = "right"
action = "toggle_format"
[[block.click]]
button = "left"
update = true

# dist space
[[block]]
merge_with_next = false 
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
[[block.click]]
button = "left"
update = true

# internet
[[block]]
merge_with_next = true 
block = "net"
# device = "wlp2s0"
format = "$icon {$ssid $signal_strength|} "
format_alt = "$icon {$ssid $signal_strength} $speed_down.eng(w:3){,}$speed_up.eng(w:3) "
interval = 20
[[block.click]]
button = "left"
update = true
[[block.click]]
button = "right"
update = true
action = "toggle_format"

# bluetooth
[[block]]
merge_with_next = true 
block = "bluetooth"
mac = "84:AC:60:31:89:58"
disconnected_format = "$icon -"
format = " $icon $name { $percentage|}"
[block.battery_state]
"0..20" = "critical"
"21..22" = "warning"
"23..100" = "good"
[[block.click]]
button = "left"
update = true

# volume
[[block]]
merge_with_next = true 
block = "sound"
format = " $icon {$volume.eng(w:2)|} "
[[block.click]]
button = "right"
cmd = "pavucontrol"
[[block.click]]
button = "up"
action = "volume_up"
[[block.click]]
button = "down"
action = "volume_down"

# battery
[[block]]
merge_with_next = false 
block = "battery"

# not full and unpluged format
format = " $icon {$percentage} "

# full_format = " $icon "
# charging_format = " $icon {$percentage|} "
# empty_format = " $icon {$percentage|} "
# not_charging_format = " $icon {$percentage|} "

# full battery format
full_format = "$icon {$percentage.eng(w:2)|}"
# not full and pluged in format
charging_format = "$icon {$percentage|}"
# empty and not plugged in format
empty_format = "$icon {$percentage|}"
# when full battery has reached
not_charging_format = "$icon {$percentage|}"

full_threshold = 80
empty_threshold = 60

device = "DisplayDevice"
driver = "upower"
interval = 60
good = 80
info = 80
warning = 65
critical = 60
[[block.click]]
button = "left"
update = true

[[block]]
block = "time"
interval = 60
format = " $timestamp.datetime(f:'%a %-d-%b %I:%M %P') "
