[colors.bright]
black = "#4C566A"
blue = "#81A1C1"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#ECEFF4"
yellow = "#EBCB8B"

[colors.cursor]
cursor = "#00CACA"
text = "#000000"

[colors.normal]
black = "#156BDC"
blue = "#F77067"
cyan = "#88C0D0"
green = "#2AACAA"
magenta = "#B48EAD"
red = "#F22C57"
white = "#E5E9F0"
yellow = "#EBCB8B"

[colors.primary]
background = "#1a1b26"
foreground = "#D8DEE9"
